import { City, Venue, VenueType } from './types';

export const VENUES: Venue[] = [
  // PUNE
  {
    id: 'p1',
    name: 'Royal Banquet Palace',
    city: City.Pune,
    address: 'Balewadi, Pune',
    pricePerEvent: 95000,
    guestCapacity: 300,
    type: VenueType.BanquetHall,
    amenities: ['AC', 'Parking', 'In-house Catering', 'Changing Rooms'],
    description: 'A majestic banquet hall with crystal chandeliers and plush interiors, perfect for grand weddings and corporate galas.',
    imageUrl: 'https://picsum.photos/seed/p1/800/600',
    gallery: ['https://picsum.photos/seed/p1-1/800/600', 'https://picsum.photos/seed/p1-2/800/600', 'https://picsum.photos/seed/p1-3/800/600'],
    rating: 4.8,
    reviews: 124,
    coordinates: { lat: 18.5793, lng: 73.7676 }
  },
  {
    id: 'p2',
    name: 'Orchid Lounge',
    city: City.Pune,
    address: 'Koregaon Park, Pune',
    pricePerEvent: 70000,
    guestCapacity: 150,
    type: VenueType.Lounge,
    amenities: ['Rooftop', 'DJ Booth', 'City Views', 'Cocktail Bar'],
    description: 'Chic rooftop lounge in the heart of Koregaon Park offering stunning city views and a vibrant atmosphere for parties.',
    imageUrl: 'https://picsum.photos/seed/p2/800/600',
    gallery: ['https://picsum.photos/seed/p2-1/800/600', 'https://picsum.photos/seed/p2-2/800/600', 'https://picsum.photos/seed/p2-3/800/600'],
    rating: 4.5,
    reviews: 89,
    coordinates: { lat: 18.5362, lng: 73.8940 }
  },
  {
    id: 'p3',
    name: 'Serenity Lawns',
    city: City.Pune,
    address: 'Baner, Pune',
    pricePerEvent: 85000,
    guestCapacity: 250,
    type: VenueType.PartyLawn,
    amenities: ['Green Lawns', 'Outdoor Lighting', 'Live Music Support', 'Valet'],
    description: 'Expansive green lawns perfect for open-air receptions and cultural events under the stars.',
    imageUrl: 'https://picsum.photos/seed/p3/800/600',
    gallery: ['https://picsum.photos/seed/p3-1/800/600', 'https://picsum.photos/seed/p3-2/800/600', 'https://picsum.photos/seed/p3-3/800/600'],
    rating: 4.7,
    reviews: 56,
    coordinates: { lat: 18.5590, lng: 73.7868 }
  },
  {
    id: 'p4',
    name: 'Crystal Resort',
    city: City.Pune,
    address: 'Hinjewadi, Pune',
    pricePerEvent: 120000,
    guestCapacity: 400,
    type: VenueType.Resort,
    amenities: ['Luxury Suites', 'Poolside Bar', 'Stage', 'WiFi'],
    description: 'A premium resort offering a blend of luxury and leisure, featuring poolside event areas and grand indoor halls.',
    imageUrl: 'https://picsum.photos/seed/p4/800/600',
    gallery: ['https://picsum.photos/seed/p4-1/800/600', 'https://picsum.photos/seed/p4-2/800/600', 'https://picsum.photos/seed/p4-3/800/600'],
    rating: 4.9,
    reviews: 210,
    coordinates: { lat: 18.5913, lng: 73.7389 }
  },
  {
    id: 'p5',
    name: 'Lotus Celebrations Hall',
    city: City.Pune,
    address: 'Kothrud, Pune',
    pricePerEvent: 65000,
    guestCapacity: 120,
    type: VenueType.BanquetHall,
    amenities: ['Budget Friendly', 'Easy Parking', 'AC', 'Sound System'],
    description: 'An elegant yet affordable banquet hall ideal for intimate gatherings, birthdays, and family functions.',
    imageUrl: 'https://picsum.photos/seed/p5/800/600',
    gallery: ['https://picsum.photos/seed/p5-1/800/600', 'https://picsum.photos/seed/p5-2/800/600', 'https://picsum.photos/seed/p5-3/800/600'],
    rating: 4.2,
    reviews: 45,
    coordinates: { lat: 18.5074, lng: 73.8077 }
  },
  // BANGALORE
  {
    id: 'b1',
    name: 'Taj Heritage Banquets',
    city: City.Bangalore,
    address: 'Whitefield, Bangalore',
    pricePerEvent: 135000,
    guestCapacity: 350,
    type: VenueType.BanquetHall,
    amenities: ['Ornate Décor', 'Valet Parking', 'AC', 'Catering'],
    description: 'Experience royalty at Taj Heritage, featuring exquisite heritage architecture and world-class hospitality.',
    imageUrl: 'https://picsum.photos/seed/b1/800/600',
    gallery: ['https://picsum.photos/seed/b1-1/800/600', 'https://picsum.photos/seed/b1-2/800/600', 'https://picsum.photos/seed/b1-3/800/600'],
    rating: 4.9,
    reviews: 300,
    coordinates: { lat: 12.9698, lng: 77.7500 }
  },
  {
    id: 'b2',
    name: 'Sky High Lounge',
    city: City.Bangalore,
    address: 'MG Road, Bangalore',
    pricePerEvent: 95000,
    guestCapacity: 180,
    type: VenueType.Lounge,
    amenities: ['City Views', 'Cocktail Bar', 'Sound System', 'Dance Floor'],
    description: 'Located on MG Road, this lounge offers panoramic views of the garden city and a state-of-the-art sound system.',
    imageUrl: 'https://picsum.photos/seed/b2/800/600',
    gallery: ['https://picsum.photos/seed/b2-1/800/600', 'https://picsum.photos/seed/b2-2/800/600', 'https://picsum.photos/seed/b2-3/800/600'],
    rating: 4.6,
    reviews: 150,
    coordinates: { lat: 12.9756, lng: 77.6097 }
  },
  {
    id: 'b3',
    name: 'Gardenia Resort',
    city: City.Bangalore,
    address: 'Electronic City, Bangalore',
    pricePerEvent: 110000,
    guestCapacity: 320,
    type: VenueType.Resort,
    amenities: ['Outdoor Banquet', 'Floral Decorations', 'Pool', 'Rooms'],
    description: 'A lush green getaway in Electronic City, Gardenia Resort is perfect for destination weddings within the city.',
    imageUrl: 'https://picsum.photos/seed/b3/800/600',
    gallery: ['https://picsum.photos/seed/b3-1/800/600', 'https://picsum.photos/seed/b3-2/800/600', 'https://picsum.photos/seed/b3-3/800/600'],
    rating: 4.7,
    reviews: 98,
    coordinates: { lat: 12.8452, lng: 77.6602 }
  },
  {
    id: 'b4',
    name: 'Sapphire Hall',
    city: City.Bangalore,
    address: 'Jayanagar, Bangalore',
    pricePerEvent: 80000,
    guestCapacity: 140,
    type: VenueType.BanquetHall,
    amenities: ['Stage', 'Customizable Lighting', 'AC', 'Buffet Area'],
    description: 'Modern and stylish, Sapphire Hall provides a versatile space with customizable lighting to match your theme.',
    imageUrl: 'https://picsum.photos/seed/b4/800/600',
    gallery: ['https://picsum.photos/seed/b4-1/800/600', 'https://picsum.photos/seed/b4-2/800/600', 'https://picsum.photos/seed/b4-3/800/600'],
    rating: 4.4,
    reviews: 76,
    coordinates: { lat: 12.9250, lng: 77.5938 }
  },
  {
    id: 'b5',
    name: 'Amber Greens',
    city: City.Bangalore,
    address: 'Indiranagar, Bangalore',
    pricePerEvent: 92000,
    guestCapacity: 250,
    type: VenueType.PartyLawn,
    amenities: ['Open-air', 'Garden Setting', 'Private Parking', 'Gazebo'],
    description: 'Tucked away in Indiranagar, Amber Greens offers a serene open-air garden setting for sophisticated gatherings.',
    imageUrl: 'https://picsum.photos/seed/b5/800/600',
    gallery: ['https://picsum.photos/seed/b5-1/800/600', 'https://picsum.photos/seed/b5-2/800/600', 'https://picsum.photos/seed/b5-3/800/600'],
    rating: 4.8,
    reviews: 112,
    coordinates: { lat: 12.9784, lng: 77.6408 }
  },
  // MUMBAI
  {
    id: 'm1',
    name: 'Sea View Banquet',
    city: City.Mumbai,
    address: 'Juhu, Mumbai',
    pricePerEvent: 175000,
    guestCapacity: 400,
    type: VenueType.BanquetHall,
    amenities: ['Oceanfront', 'Terrace', 'AC', 'Valet'],
    description: 'Breathtaking ocean views meet luxury at Sea View Banquet, the ultimate destination for elite events in Juhu.',
    imageUrl: 'https://picsum.photos/seed/m1/800/600',
    gallery: ['https://picsum.photos/seed/m1-1/800/600', 'https://picsum.photos/seed/m1-2/800/600', 'https://picsum.photos/seed/m1-3/800/600'],
    rating: 4.9,
    reviews: 420,
    coordinates: { lat: 19.1031, lng: 72.8267 }
  },
  {
    id: 'm2',
    name: 'Opal Lounge',
    city: City.Mumbai,
    address: 'Lower Parel, Mumbai',
    pricePerEvent: 110000,
    guestCapacity: 160,
    type: VenueType.Lounge,
    amenities: ['Modern Interiors', 'Live Cooking', 'Bar', 'Music'],
    description: 'Situated in the business hub of Lower Parel, Opal Lounge features contemporary design and live cooking stations.',
    imageUrl: 'https://picsum.photos/seed/m2/800/600',
    gallery: ['https://picsum.photos/seed/m2-1/800/600', 'https://picsum.photos/seed/m2-2/800/600', 'https://picsum.photos/seed/m2-3/800/600'],
    rating: 4.7,
    reviews: 180,
    coordinates: { lat: 18.9977, lng: 72.8376 }
  },
  {
    id: 'm3',
    name: 'Mahogany Lawns',
    city: City.Mumbai,
    address: 'Powai, Mumbai',
    pricePerEvent: 98000,
    guestCapacity: 220,
    type: VenueType.PartyLawn,
    amenities: ['Lakeside Setting', 'Gazebo', 'Fairy Lights', 'Parking'],
    description: 'A romantic lakeside setting in Powai with beautiful fairy lights and a gazebo, perfect for evening receptions.',
    imageUrl: 'https://picsum.photos/seed/m3/800/600',
    gallery: ['https://picsum.photos/seed/m3-1/800/600', 'https://picsum.photos/seed/m3-2/800/600', 'https://picsum.photos/seed/m3-3/800/600'],
    rating: 4.6,
    reviews: 140,
    coordinates: { lat: 19.1176, lng: 72.9060 }
  },
  {
    id: 'm4',
    name: 'Iconic Palace',
    city: City.Mumbai,
    address: 'Andheri East, Mumbai',
    pricePerEvent: 128000,
    guestCapacity: 350,
    type: VenueType.BanquetHall,
    amenities: ['Luxury Interiors', 'Valet', 'VIP Suite', 'Catering'],
    description: 'Iconic Palace offers grandeur and opulence with its high ceilings, gold accents, and dedicated VIP suites.',
    imageUrl: 'https://picsum.photos/seed/m4/800/600',
    gallery: ['https://picsum.photos/seed/m4-1/800/600', 'https://picsum.photos/seed/m4-2/800/600', 'https://picsum.photos/seed/m4-3/800/600'],
    rating: 4.8,
    reviews: 255,
    coordinates: { lat: 19.1136, lng: 72.8697 }
  },
  {
    id: 'm5',
    name: 'Sunshine Events Hall',
    city: City.Mumbai,
    address: 'Dadar, Mumbai',
    pricePerEvent: 68000,
    guestCapacity: 100,
    type: VenueType.BanquetHall,
    amenities: ['Affordable', 'City Center', 'AC', 'Decoration'],
    description: 'Conveniently located in Dadar, Sunshine Events Hall is a budget-friendly choice without compromising on quality.',
    imageUrl: 'https://picsum.photos/seed/m5/800/600',
    gallery: ['https://picsum.photos/seed/m5-1/800/600', 'https://picsum.photos/seed/m5-2/800/600', 'https://picsum.photos/seed/m5-3/800/600'],
    rating: 4.3,
    reviews: 67,
    coordinates: { lat: 19.0178, lng: 72.8478 }
  }
];